use_frameworks!

platform :ios, '13.0'

target 'Learn_Combine_Example' do
  pod 'Learn_Combine', :path => '../'
  pod 'CocoaLumberjack/Swift'

  target 'Learn_Combine_Tests' do
    inherit! :search_paths

    
  end
end
